services:
  # Backend API Service
  - type: web
    name: memory-palace-api
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    rootDir: server
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: STABILITY_API_KEY
        sync: false
      - key: PORT
        value: 10000
    healthCheckPath: /api/health

  # Frontend Web Service
  - type: web
    name: low-sai
    env: static
    plan: starter
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://memory-palace-api.onrender.com
