/**
 * PROMPT ENHANCER SERVICE
 *
 * PURPOSE: Takes a simple anchor+memorable item and uses OpenAI's GPT
 * to transform it into a creative, bizarre prompt for image generation
 *
 * EXAMPLE:
 *   Input: { anchor: "Piano", memorableItem: "George Washington" }
 *   Output: "A figure resembling George Washington intensely washing
 *            an enormous piano with a washbrush, soap suds flying..."
 *
 * PATTERN: This follows the same structure as embeddingService.js
 * - Import dependencies
 * - Set up API config
 * - Export main function
 * - Handle errors gracefully
 */

const axios = require('axios');
require('dotenv').config();

// ============================================================
// CONFIGURATION SECTION
// ============================================================

// TODO #1: Get OpenAI API key from environment
// Look at how STABILITY_API_KEY is used in imageController.js
// What environment variable should we use here?
const OPENAI_API_KEY = process.env.OPENAI_API_KEY;

// The endpoint we'll call to generate creative prompts
const OPENAI_API_URL = 'https://api.openai.com/v1/chat/completions';

// This is the "system prompt" - it tells GPT what role to play
// Think of this as instructions for how GPT should behave
const SYSTEM_PROMPT = `You are a creative director for a memory palace visualization system.
Your job is to take simple anchor points (objects in a room) and memorable items (things to remember)
and transform them into bizarre, exaggerated, highly visual metaphors that are memorable and creative.

The images will be generated by an AI artist, so your descriptions should be:
- Visually descriptive (colors, sizes, movements, emotions)
- Exaggerated and unusual (bigger, stranger, more emotional than real life)
- Action-oriented (something HAPPENING, not just sitting there)
- Specific (not generic)

Example: If anchor="Piano" and memorable="George Washington", you might say:
"A figure resembling George Washington, wearing a tricorn hat, intensely washing
an enormous grand piano with a giant scrub brush. Soap suds are flying everywhere.
The piano is absurdly oversized. George's face shows intense concentration.
The background is a 1700s living room with candles flickering."

Keep responses to 1-2 sentences.`;

// ============================================================
// MAIN FUNCTION - This is what gets called from imageController
// ============================================================

/**
 * enhancePrompt()
 *
 * INPUTS:
 *   - anchor: string (e.g., "Piano")
 *   - memorableItem: string (e.g., "George Washington")
 *
 * OUTPUTS:
 *   - enhancedPrompt: string (the creative prompt)
 *   - OR throws an error if something goes wrong
 *
 * FLOW:
 *   1. Check if API key exists
 *   2. Build the user message to send to GPT
 *   3. Call OpenAI API via axios
 *   4. Extract the response text
 *   5. Return it (or return original if error)
 */

exports.enhancePrompt = async (anchor, memorableItem) => {
  try {
    // TODO #2: Fallback handling
    // If OpenAI key is missing, what should we do?
    // Option A: Throw an error
    // Option B: Return the simple prompt (anchor + memorableItem)
    // Option C: Try a local enhancement
    //
    // For now, let's go with option B - return the simple prompt
    // This is good UX - feature degrades gracefully if API fails

    if (!OPENAI_API_KEY) {
      console.warn('OPENAI_API_KEY not configured, returning simple prompt');
      // TODO #2 ANSWER: Build a simple fallback prompt
      // Something like: `${anchor}: ${memorableItem}`
      // or more creative: `${memorableItem} interacting with a ${anchor}`
      return `${memorableItem} interacting with a ${anchor}`;
    }

    // TODO #3: Build the user message
    // This is what we send to GPT to ask for enhancement
    // It should tell GPT: "Here's an anchor and memorable item, make it creative"
    //
    // Example format:
    // "Anchor point: Piano | Memorable item: George Washington | Create a creative, visual prompt"
    const userMessage = `TODO #3: Build a message that includes anchor and memorableItem`;

    console.log('Calling OpenAI API to enhance prompt...');

    // TODO #4: Make the API call
    // This is the key part! Here's the structure:
    //
    // const response = await axios({
    //   method: 'post',
    //   url: OPENAI_API_URL,
    //   headers: {
    //     'Content-Type': 'application/json',
    //     'Authorization': `Bearer ${OPENAI_API_KEY}`
    //   },
    //   data: {
    //     model: 'gpt-4-mini',  // or 'gpt-4' if you have it
    //     messages: [
    //       { role: 'system', content: SYSTEM_PROMPT },
    //       { role: 'user', content: userMessage }
    //     ],
    //     temperature: 0.7,  // Higher = more creative (0-1 scale)
    //     max_tokens: 150    // Limit response length
    //   }
    // });
    //
    // YOUR JOB: Write this axios call (copy the pattern above)

    // TODO #4 ANSWER HERE - Replace this comment with the axios call
    const response = null; // PLACEHOLDER

    // TODO #5: Extract the response
    // OpenAI returns data in this structure:
    // response.data.choices[0].message.content
    //
    // That's the actual text response from GPT
    // YOUR JOB: Extract it into a variable called 'enhancedPrompt'

    const enhancedPrompt = null; // PLACEHOLDER - extract from response

    console.log('Enhanced prompt:', enhancedPrompt);
    return enhancedPrompt;

  } catch (error) {
    // TODO #6: Error handling
    // If something goes wrong (API error, network issue, etc)
    // what should we do?
    //
    // Good options:
    // A) Log the error and return a simple fallback prompt
    // B) Log and throw to let caller handle it
    // C) Log and return the original prompt
    //
    // For robustness, option A is best - don't let one API failing break image generation

    console.error('Error enhancing prompt:', error.message);

    // TODO #6 ANSWER: Return a fallback
    // Suggestion: return the simple prompt as fallback
    return `${memorableItem} interacting with a ${anchor}`;
  }
};

// ============================================================
// SUMMARY OF YOUR TASKS
// ============================================================
/*
TODO #1: Find the environment variable name for OpenAI API key
         Hint: Check your .env file or what you set OPENAI_API_KEY to

TODO #2: Decide on fallback behavior
         Currently returns simple prompt - that's good!

TODO #3: Build a clear user message
         Format should be something like:
         "Anchor point: ${anchor}, Memorable item: ${memorableItem},
          Create a bizarre, visual description..."

TODO #4: Write the axios call to OpenAI
         Copy the pattern from imageController.js
         Use the structure provided in comments above

TODO #5: Extract the response
         Get: response.data.choices[0].message.content

TODO #6: Error handling
         Already outlined - graceful fallback

That's it! Once you fill these in, this service is done.
Next step: We modify imageController.js to USE this service.
*/
