/**
 * PROMPT ENHANCER SERVICE
 *
 * Uses Anthropic Claude (Messages API) to turn anchor + memorable item
 * into a short, vivid image prompt. Falls back to a simple template if
 * ANTHROPIC_API_KEY is missing or the request fails.
 */

const axios = require('axios');
require('dotenv').config();

const ANTHROPIC_API_KEY = process.env.ANTHROPIC_API_KEY;
/**
 * Model IDs change over time — see https://platform.claude.com/docs/en/about-claude/models/overview
 * - Default: Haiku 4.5 (fast / lower cost; good for short prompt expansion on every click).
 * - For parity with Claude chat “Opus 4.7”: set ANTHROPIC_MODEL=claude-opus-4-7
 * - Balanced: claude-sonnet-4-6
 */
const ANTHROPIC_MODEL =
  process.env.ANTHROPIC_MODEL || 'claude-haiku-4-5';
const ANTHROPIC_API_URL = 'https://api.anthropic.com/v1/messages';
/** API versions: https://docs.anthropic.com/en/api/versioning */
const ANTHROPIC_VERSION = process.env.ANTHROPIC_VERSION || '2023-06-01';

const REQUEST_TIMEOUT_MS = 25000;

const SYSTEM_PROMPT = `You are a creative director for a memory palace visualization system.
Your job is to take simple anchor points (objects in a room) and memorable items (things to remember)
and transform them into bizarre, exaggerated, highly visual metaphors that are memorable and creative.

The images will be generated by an AI artist, so your descriptions should be:
- Visually descriptive (colors, sizes, movements, emotions)
- Exaggerated and unusual (bigger, stranger, more emotional than real life)
- Action-oriented (something HAPPENING, not just sitting there)
- Specific (not generic)

Output rules:
- Reply with exactly ONE English sentence suitable as a Stable Diffusion / SDXL image prompt.
- No preamble, no title, no markdown, no JSON wrapper—only the sentence.`;

function fallbackPrompt(anchor, memorableItem) {
  return `${memorableItem} interacting with a ${anchor}`;
}

function extractTextFromMessage(responseData) {
  const blocks = responseData?.content;
  if (!Array.isArray(blocks)) return '';
  const texts = blocks
    .filter((b) => b && b.type === 'text' && typeof b.text === 'string')
    .map((b) => b.text);
  return texts.join('\n').trim();
}

/**
 * @param {string} anchor
 * @param {string} memorableItem
 * @returns {Promise<string>}
 */
exports.enhancePrompt = async (anchor, memorableItem) => {
  if (!anchor || !memorableItem) {
    return fallbackPrompt(anchor || 'object', memorableItem || 'subject');
  }

  if (!ANTHROPIC_API_KEY) {
    console.warn('ANTHROPIC_API_KEY not configured, using fallback prompt');
    return fallbackPrompt(anchor, memorableItem);
  }

  const userMessage = `Anchor point: ${anchor}
Memorable item: ${memorableItem}

Write the single-sentence image prompt described in your instructions.`;

  try {
    const response = await axios({
      method: 'post',
      url: ANTHROPIC_API_URL,
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': ANTHROPIC_API_KEY,
        'anthropic-version': ANTHROPIC_VERSION
      },
      data: {
        model: ANTHROPIC_MODEL,
        max_tokens: 256,
        temperature: 0.75,
        system: SYSTEM_PROMPT,
        messages: [{ role: 'user', content: userMessage }]
      },
      timeout: REQUEST_TIMEOUT_MS
    });

    const text = extractTextFromMessage(response.data);
    if (!text) {
      console.warn('Claude returned empty content, using fallback prompt');
      return fallbackPrompt(anchor, memorableItem);
    }

    return text;
  } catch (error) {
    const status = error.response?.status;
    const body = error.response?.data;
    console.error('Error enhancing prompt with Claude:', error.message, {
      status,
      body: typeof body === 'object' ? body : undefined
    });
    return fallbackPrompt(anchor, memorableItem);
  }
};
