import React from 'react';
import LegalPage from './LegalPage';

const TermsOfService = () => {
  return (
    <LegalPage title="Terms of Service">
      <p><strong>Effective Date: [Current Date]</strong></p>

      <h2>1. Acceptance of Terms</h2>
      <p>
        Welcome to Low·sAI (Memory Palace). By accessing or using our website, mobile application, or any related services (collectively, the "Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, please do not use our Service.
      </p>

      <h2>2. Description of Service</h2>
      <p>
        Low·sAI is an AI-powered memory palace application that helps users create and use the method of loci (memory palace technique) to improve memory and learning. Our Service includes:
      </p>
      <ul>
        <li>AI-powered image generation for memory associations</li>
        <li>Interactive memory palace creation and visualization</li>
        <li>Storage and management of user-created memory palaces</li>
        <li>Educational content about memory techniques</li>
      </ul>

      <h2>3. User Accounts and Registration</h2>

      <h3>3.1 Account Creation</h3>
      <ul>
        <li>You may use our Service in demo mode without creating an account</li>
        <li>To access full features, you may be required to create an account</li>
        <li>You must provide accurate, current, and complete information during registration</li>
        <li>You are responsible for maintaining the confidentiality of your account credentials</li>
      </ul>

      <h3>3.2 Account Responsibilities</h3>
      <ul>
        <li>You are responsible for all activities that occur under your account</li>
        <li>You must notify us immediately of any unauthorized use of your account</li>
        <li>You may not share your account credentials with others</li>
        <li>You must be at least 13 years old to create an account</li>
      </ul>

      <h2>4. Acceptable Use Policy</h2>

      <h3>4.1 Permitted Uses</h3>
      <p>You may use our Service for:</p>
      <ul>
        <li>Personal learning and memory improvement</li>
        <li>Educational purposes</li>
        <li>Creating and managing your own memory palaces</li>
        <li>Sharing content in accordance with these Terms</li>
      </ul>

      <h3>4.2 Prohibited Uses</h3>
      <p>You may not use our Service to:</p>
      <ul>
        <li>Violate any applicable laws or regulations</li>
        <li>Infringe on intellectual property rights</li>
        <li>Create content that is harmful, offensive, or inappropriate</li>
        <li>Attempt to gain unauthorized access to our systems</li>
        <li>Interfere with the proper functioning of the Service</li>
        <li>Generate content that promotes violence, discrimination, or illegal activities</li>
        <li>Use the Service for commercial purposes without our written permission</li>
      </ul>

      <h2>5. User-Generated Content</h2>

      <h3>5.1 Content Ownership</h3>
      <ul>
        <li>You retain ownership of the content you create using our Service</li>
        <li>You grant us a limited license to store and process your content to provide the Service</li>
        <li>You are responsible for ensuring you have the right to use any content you input</li>
      </ul>

      <h3>5.2 Content Guidelines</h3>
      <ul>
        <li>Content must be appropriate and not violate any laws or regulations</li>
        <li>You may not upload or create content that infringes on others' rights</li>
        <li>We reserve the right to remove content that violates these Terms</li>
      </ul>

      <h3>5.3 AI-Generated Content</h3>
      <ul>
        <li>Images generated by our AI are created based on your input</li>
        <li>You may use AI-generated images for personal, non-commercial purposes</li>
        <li>Commercial use of AI-generated images may be subject to additional terms</li>
      </ul>

      <h2>6. Intellectual Property</h2>

      <h3>6.1 Our Rights</h3>
      <ul>
        <li>The Service, including its design, functionality, and content, is owned by Low·sAI</li>
        <li>Our trademarks, logos, and brand elements are protected by intellectual property laws</li>
        <li>You may not use our intellectual property without written permission</li>
      </ul>

      <h3>6.2 Your Rights</h3>
      <ul>
        <li>You retain ownership of your user-generated content</li>
        <li>You may use AI-generated images for personal purposes as outlined in these Terms</li>
      </ul>

      <h2>7. Privacy and Data Protection</h2>
      <p>
        Your privacy is important to us. Our collection and use of personal information is governed by our Privacy Policy, which is incorporated into these Terms by reference.
      </p>

      <h2>8. Service Availability and Modifications</h2>

      <h3>8.1 Service Availability</h3>
      <ul>
        <li>We strive to maintain high service availability but cannot guarantee uninterrupted access</li>
        <li>We may temporarily suspend the Service for maintenance or updates</li>
        <li>We are not liable for any damages resulting from service interruptions</li>
      </ul>

      <h3>8.2 Service Modifications</h3>
      <ul>
        <li>We may modify, suspend, or discontinue the Service at any time</li>
        <li>We will provide reasonable notice of significant changes when possible</li>
        <li>Continued use of the Service after changes constitutes acceptance of new terms</li>
      </ul>

      <h2>9. Payment Terms (Future Feature)</h2>

      <h3>9.1 Subscription Services</h3>
      <ul>
        <li>Premium features may be offered on a subscription basis</li>
        <li>Subscription fees will be clearly disclosed before purchase</li>
        <li>Payments are non-refundable except as required by law</li>
      </ul>

      <h3>9.2 Billing</h3>
      <ul>
        <li>Subscription fees are charged in advance on a recurring basis</li>
        <li>You may cancel your subscription at any time</li>
        <li>Failure to pay may result in service suspension or termination</li>
      </ul>

      <h2>10. Disclaimers and Limitations of Liability</h2>

      <h3>10.1 Service Disclaimers</h3>
      <ul>
        <li>The Service is provided "as is" without warranties of any kind</li>
        <li>We do not guarantee the accuracy or effectiveness of memory techniques</li>
        <li>AI-generated content may not always be accurate or appropriate</li>
        <li>We are not responsible for the success or failure of memory improvement efforts</li>
      </ul>

      <h3>10.2 Limitation of Liability</h3>
      <ul>
        <li>To the maximum extent permitted by law, Low·sAI shall not be liable for any indirect, incidental, special, consequential, or punitive damages</li>
        <li>Our total liability shall not exceed the amount paid by you for the Service in the 12 months preceding the claim</li>
      </ul>

      <h2>11. Indemnification</h2>
      <p>
        You agree to indemnify and hold harmless Low·sAI, its officers, directors, employees, and agents from any claims, damages, or expenses arising from:
      </p>
      <ul>
        <li>Your use of the Service</li>
        <li>Your violation of these Terms</li>
        <li>Your violation of any third-party rights</li>
      </ul>

      <h2>12. Termination</h2>

      <h3>12.1 Termination by You</h3>
      <ul>
        <li>You may stop using the Service at any time</li>
        <li>You may delete your account through the Service interface</li>
      </ul>

      <h3>12.2 Termination by Us</h3>
      <ul>
        <li>We may terminate or suspend your access to the Service for violations of these Terms</li>
        <li>We may terminate the Service with reasonable notice</li>
        <li>Upon termination, your right to use the Service ceases immediately</li>
      </ul>

      <h3>12.3 Effect of Termination</h3>
      <ul>
        <li>Your account and data may be permanently deleted</li>
        <li>You may lose access to your memory palaces and content</li>
        <li>Provisions of these Terms that survive termination remain in effect</li>
      </ul>

      <h2>13. Governing Law and Dispute Resolution</h2>

      <h3>13.1 Governing Law</h3>
      <p>
        These Terms are governed by the laws of [Your Jurisdiction], without regard to conflict of law principles.
      </p>

      <h3>13.2 Dispute Resolution</h3>
      <ul>
        <li>Disputes will be resolved through binding arbitration</li>
        <li>Arbitration will be conducted in [Your Jurisdiction]</li>
        <li>You waive any right to a jury trial or class action lawsuit</li>
      </ul>

      <h2>14. Changes to Terms</h2>

      <h3>14.1 Notification of Changes</h3>
      <ul>
        <li>We may update these Terms from time to time</li>
        <li>We will notify users of significant changes via email or in-app notification</li>
        <li>Continued use of the Service after changes constitutes acceptance</li>
      </ul>

      <h3>14.2 Review of Changes</h3>
      <ul>
        <li>Users are encouraged to review Terms periodically</li>
        <li>Previous versions of Terms will be available upon request</li>
      </ul>

      <h2>15. Contact Information</h2>
      <p>For questions about these Terms of Service, please contact us:</p>

      <p><strong>Low·sAI</strong></p>
      <ul>
        <li>Email: [legal@lowsai.com]</li>
        <li>Address: [Your Business Address]</li>
        <li>Website: [www.lowsai.com]</li>
      </ul>

      <h2>16. Severability</h2>
      <p>
        If any provision of these Terms is found to be unenforceable, the remaining provisions will continue in full force and effect.
      </p>

      <h2>17. Entire Agreement</h2>
      <p>
        These Terms constitute the entire agreement between you and Low·sAI regarding the Service and supersede all prior agreements and understandings.
      </p>

      <hr />

      <p><strong>Last Updated: [Current Date]</strong></p>
    </LegalPage>
  );
};

export default TermsOfService;
